### ISSUE TITLE
pvcam: bugged readout time

### ISSUE THREAD

**Issue by dstoychev** [python-microscope/microscope#200]
There is a bug in the PVCAM SDK. The parameter `PARAM_READOUT_TIME` is defined as 64-bit float, but it's actually an unsigned 32-bit integer. Here is what the SDK documentation says:

>The parameter type is incorrectly defined. The actual type is TYPE_UNS32.

Because we determine the type from this (wrong) definition, the value is not interpreted correctly. Instead of overhauling the entire parameter system, the easiest solution seems to be to add a simple check that corrects the type for this parameter only. An example implementation is in dstoychev/microscope@b13228db6068df7058b3ccf542013575280fb529.

**Comment by iandobbie** [comment]
Pulled fix into master
