### ISSUE TITLE
SDK3 is causing client to look for ATCore.DLL

### ISSUE THREAD

**Issue by mickp** [python-microscope/microscope#21]
I suspect it's trying to send back an exception which involves some call or value from the DLL.

Replication: try to set the AOI_Binning parameter from cockpit settings panel with a camera on a remote machine. If microscope is not installed on the client machine, you'll see a 'no module mircroscope.SDK3' error; if it is installed but without the SDK3 DLL, you'll see a 'specified module could not be found' error.

We should make sure that, in the event of an exception, the remote sends back useful messages rather than references to objects in the microscope package.

**Comment by iandobbie** [comment]
This is a very old bug report and I no longer have access to the relevant hardware so I am close this issue.
