### ISSUE TITLE
Device server on Raspberry Pi

### ISSUE THREAD

**Issue by rreeves60** [python-microscope/microscope#241]
I just wondered if a device server could run on Raspberry pi. If this has not been tested I will attempt to compile the python script on rasperian

**Comment by rreeves60** [comment]
I work for Martin booth

**Comment by rreeves60** [comment]
I also see some work has been done for PiCam will also check this out.

**Comment by iandobbie** [comment]
The device server will definitely run on a raspberry pi and some hardware is supported typically hardware that talks serial or serial over USB. Other USB devices might be supported but they may lack drivers for linux in general or the Pi in particular. One other thing to consider is that devices with significant IO or processing requirements maybe slow and even the new fast Pi4 is not very fast compared to the multi core desktop or laptop machine.
