### ISSUE TITLE
Need to be able to set hardware and software triggers to work from cockpit. 

### ISSUE THREAD

**Issue by iandobbie** [python-microscope/microscope#244]
We have discussed this point before but I think we do need a method in cockpit switch a generic triggered microscope device from software to hardware trigger mode.

For instance if you set a camera as hardware triggered in your depot.conf there is no way to then utilise a software trigger on this camera. Additionally by default the camera will probably start in software trigger mode as most devices seem to do that.

I think we need at least:
1) Method to switch a microscope device between hardware and software trigger modes that does so at both cockpit and microscope ends. 

2) Method to set microscope device triggers to software or hardware at startup, presumable from their depot config. This should utilise the code in 1.

**Comment by carandraug** [comment]
This is actually a cockpit issue already open at MicronOxford/cockpit#816. Closing.
