### ISSUE TITLE
Mutex error when opening Ximea camra

### ISSUE THREAD

**Issue by dijo1998** [python-microscope/microscope#253]
Hi all,
I am trying to connect to a Ximea xiQ camera using python microscope. But I am getting error saying "ERROR 57: Resource (device) or function locked by mutex" . This ha[[ens for the line of code which opens the device. I also tried with xiAPI Python. But the result is same error.
Can someone help me solve this issue.
@carandraug

**Comment by carandraug** [comment]
Double post from https://forum.image.sc/t/ximea-camera-xiapi-python-python-microscope/72093/2 As this does not appear to be an issue in Python-Microscope (because it can be reproduce using xiApiPython alone), let's continue the discussion there.
