### ISSUE TITLE
support for Hamamatsu cameras

### ISSUE THREAD

**Issue by carandraug** [python-microscope/microscope#38]
Requested at ELMI 2018.

I'm told that Hamamatsu dCamAPI library supports all of their cameras.

**Comment by carandraug** [comment]
Requested again, twice, at SPAOM 2019.

**Comment by carandraug** [comment]
Met with @maazevedo who requested support for an Hamamatsu Orca flash 4.0.  I looked into [dcam-api](https://dcam-api.com/structure/) who claims to support both Windows and Linux but downloads only shows windows support. I have emailed Hamamatsu about where I can find the Linux builds.

**Comment by carandraug** [comment]
MesoSPIM (GPLv3) have a [ctypes wrapper to dcam-api](https://github.com/mesoSPIM/mesoSPIM-control/blob/master/mesoSPIM/src/devices/cameras/hamamatsu/hamamatsu_camera.py).

**Comment by carandraug** [comment]
I have just spoken with [James R Brown from Hamamatsu](mailto:JRBrown@hamamatsu.co.uk) at QBI2020 who offered to lend us their cameras for a few months if we need them to do this.

**Comment by juliomateoslangerak** [comment]
Had a visit from Hamamatsu representative last week and he mentioned that there will be a Python interface for their cameras very soon.

**Comment by carandraug** [comment]
@ARCFaria got an Hamamatsu camera is planning on doing this over the next weeks. @kasasxav was also interested to test the use of Microscope as hardware layer for ImSwitch.

**Comment by kasasxav** [comment]
Yes! We use a similar [ctypes-wraper to dcam-api](https://github.com/kasasxav/ImSwitch/blob/master/imswitch/imcontrol/model/interfaces/hamamatsu.py) which we borrowed from [Zhuang Lab / Babcock Lab](MIT license - https://github.com/ZhuangLab/storm-control), and then we have an intermediate class [Hamamatsu Manager](https://github.com/kasasxav/ImSwitch/blob/master/imswitch/imcontrol/model/managers/detectors/HamamatsuManager.py) to translate that into the functions we use (crop, getLatestFrame, etc).

I think something similar can be delegated to Python-Microscope and then we can directly fetch it from there. We also have Hamamatsu cameras so we debug experimentally.

**Comment by carandraug** [comment]
It took a while but it's now merged. It was only tested on Linux and with software triggers though. Closing.
