### ISSUE TITLE
Deepstar comms issues

### ISSUE THREAD

**Issue by mickp** [python-microscope/microscope#58]
Following on from MicronOxford/cockpit#369.

Julio finds that the Deepstar comms work only if he adds a 0.2s delay into write, but at a point where it should have no real effect. Without this delay, it looks like responses are either echos of the laser command (e.g. see the 'power response' lines in the loging output posted at MicronOxford/microscope#369), or junk.

I've asked him to test it without the delay, with a microscope version at or after 849316ec897132825068d0601fbe4714bc5be02a.

If it works, great - the problem was resolved by 849316ec897132825068d0601fbe4714bc5be02a.

If it doesn't work, my suspicion is that it's something to do with either the comms config that Julio is using (does his USB serial adapter do some local echo thing?), or with the DeepStar's three-state business (although I've no idea why it works fine at Oxford, in that case):

 * state 0, S0, an error state - expects 16-byte commands incl. CR/LF
 * state 1, S1, state after successful boot/reset  - expects 16-byte commands incl. CR/LF
 * state 2, S2, state after successful LASER ON - expects 7-byte commands incl. CR/LF

If Julio's test is not successful, then we need to keep track of laser state, and pad the command strings to the appropriate width ... although how do you decide what width string to send when you first fire up the software and don't know the laser state?

**Comment by iandobbie** [comment]
I didn't look at the existing code, I'm sure its fine. We can ask Tom to test the Diamond system which does have DeepStars. There is definitely an assumption that the lasers are only being operated in digital mode which was how we were using them in Oxford/Diamond. Yes this could easily be config based but would need some planning to ensure that Diamond system continued to work as expected.
